config/routes.rb
# frozen_string_literal: true

# rubocop:disable BlockLength
Rails.application.routes.draw do
  namespace :admin do
    resources :users
    resources :draws
    resources :draw_memberships
    resources :groups
    resources :memberships
    resources :clips
    resources :lottery_assignments
    resources :suites
    resources :rooms
    resources :room_assignments
    resources :buildings
    resources :colleges

    root to: 'users#index'
  end

  devise_for :users
  unauthenticated :user do
    root to: 'colleges#show', id: 'home', as: 'landing_page'
  end
  root to: 'dashboards#show'

  resources :colleges, only: %i(show index new create edit update) do
    patch 'archive'
  end

  shallow do
    resources :buildings do
      resources :suites, except: :index do
        member do
          get 'merge'
          post 'merge', to: 'suites#perform_merge'
          get 'split'
          post 'split', to: 'suites#perform_split'
          post 'unmerge'
        end
        resources :rooms, except: :index do
          member do
            patch 'suite', to: 'rooms#update'
            post 'suite', to: 'rooms#update'
          end
        end
      end
    end
  end

  resource :suite_import, only: %i(create)

  resource :terms_of_service, only: %i(show) do
    patch 'accept'
    patch 'reset'
  end

  resources :masquerades, only: %() do
    collection do
      delete 'end', to: 'masquerades#end', as: 'end'
    end
  end

  resources :users do
    resources :masquerades, only: %i(new)

    member do
      get 'intent', to: 'users#edit_intent', as: 'edit_intent'
      patch 'intent', to: 'users#update_intent', as: 'update_intent'
      get 'edit_password'
      patch 'update_password'
    end

    collection do
      get 'build'
    end
  end

  resources :enrollments, only: %i(new create)

  resources :draws, only: %i(new create show edit update destroy) do
    member do
      patch 'activate'
      post 'duplicate'
      patch 'proceed_to_group_formation'
      post 'reminder'
      patch 'bulk_on_campus'
      get 'lottery_confirmation'
      patch 'start_lottery'
      get 'oversubscription', to: 'draws#oversubscription', as: 'oversub'
      patch 'size_lock/:size', to: 'draws#toggle_size_restrict',
                               as: 'toggle_size_restrict'
      patch 'restrict_all_sizes'
      patch 'lock_all_groups'
      delete 'prune_oversub/:prune_size', to: 'draws#prune', as: 'prune'
      patch 'start_selection'
      get 'results'
      get 'group_export'
      patch 'archive'
    end

    resources :draw_suites, only: %i(index), as: :suites do
      collection do
        get 'edit_collection'
        patch 'update_collection'
      end
    end

    resources :lottery_assignments, only: %i(update create index) do
      collection do
        post 'automatic'
      end
    end

    resource :students, only: %i(edit update), controller: :draw_students do
      collection do
        patch 'bulk_assign'
      end
    end

    resources :groups do
      member do
        put 'finalize'
        put 'lock'
        put 'unlock'
        patch 'make_drawless'
        patch 'skip'
      end
    end

    resource :intents, only: [] do
      get 'report'
      post 'import'
      get 'export'
    end

    resource :suite_assignment, only: %i(new create)
  end

  resources :clips, only: %i(show edit update destroy)

  resources :clip_memberships, only: %i(update destroy)

  resources :groups, controller: 'drawless_groups' do
    collection do
      patch 'archive'
    end

    member do
      put 'lock'
      put 'unlock'
      get 'invite', to: 'memberships#new_invite', as: 'new_invite'
      post 'invite', to: 'memberships#create_invite', as: 'create_invite'
    end
    resources :memberships, only: %i(create update destroy)
    resource :suite_assignment, only: %i(new create destroy)
    resource :clip, only: %i(new create)
    resource :room_assignment, only: %i(new create edit update) do
      collection do
        get 'confirm'
      end
    end
  end

  resource :email_export, only: %i(new create)

  resources :results, only: [] do
    collection do
      get 'students'
      get 'suites'
      get 'export'
    end
  end
end

app/controllers/intents_controller.rb
# frozen_string_literal: true

# Controller for Intents
class IntentsController < ApplicationController
  prepend_before_action :set_draw

  def report
    @intents_importer = IntentsImportForm.new(students: nil)
    @students_by_intent = UsersByIntentQuery.new(@draw.students).call
    @intent_metrics = @students_by_intent.transform_values(&:count)
  end

  def import
    result = IntentsImportForm.import(students: @draw.students,
                                      file: intents_import_params['file'].path)
    handle_action(path: report_draw_intents_path(@draw), **result)
  end

  def export
    @students = @draw.students.order('draw_memberships.intent', :last_name)
    attributes = %I[#{User.login_attr} student_id last_name first_name intent]
    result = CSVGenerator.generate(data: @students, attributes: attributes,
                                   name: 'intents')
    handle_file_action(**result)
  end

  private

  def authorize!
    authorize :intent
  end

  def set_draw
    @draw = Draw.includes(students: %i(group draw)).find(params[:draw_id])
  end

  def intents_import_params
    params.require(:intents_import_form).permit(:file)
  end
end

app/views/intents/_intent_form.html.erb
<%= simple_form_for user, url: update_intent_user_path(user), remote: :true do |f| %>
  <%= f.input :intent, collection: DrawMembership.intents.keys, label_method: :humanize, as: :select, input_html: { class: 'autosubmitme' } %>
<% end %>

app/views/intents/report.html.erb
<% provide(:title, "#{@draw.name} - Intent Report" ) %>
<h1 class="draw-name"><%= @draw.name %> - Intent Report</h1>
<div class="intent-report">
  <p>You can view and update the intents of students <strong>who are not in a group</strong> below. Note that selecting a different option in the dropdown menu will <em>immediately</em> change that student's intent.</p>
  <hr />
  <% if @students_by_intent.empty? %>
    <p>There are no students in this draw yet!</p>
  <% else %>
    <ul class="tabs" data-tabs id="student-intent-tabs">
      <% @intent_metrics.each do |intent, count| %>
        <li class="tabs-title<%= @intent_metrics.keys.first == intent ? ' is-active' : '' %>">
        <a href="#students-<%= intent %>"<%= @intent_metrics.keys.first == intent ? ' aria-selected=true' : '' %>><%= "#{intent.humanize} (#{count})" %></a>
        </li>
      <% end %>
    </ul>
    <div class="tabs-content" data-tabs-content="student-intent-tabs">
      <% @intent_metrics.each do |intent, count| %>
        <div class="tabs-panel<%= @intent_metrics.keys.first == intent ? ' is-active' : '' %>" id="students-<%= intent %>">
          <h2><%= intent.humanize %> (<%= pluralize(count, 'student') %>)</h2>
          <table aria-label="Student Intents">
            <thead>
              <tr>
                <th scope="col">Last Name</th>
                <th scope="col">First Name</th>
                <th scope="col">Intent</th>
              </tr>
            </thead>
            <tbody>
              <% @students_by_intent[intent].each do |student| %>
                <tr class="<%= student.intent %>">
                  <th scope="row" data-role="student-last_name"><%= student.last_name %></th>
                  <td data-role="student-first_name"><%= student.first_name %></td>
                  <% if policy(student).update_intent? %>
                    <td class="intent-form" id="intent-form-<%= student.id %>" data-role="student-intent"><%= render 'intent_form', user: student %></td>
                  <% else %>
                    <td data-role="student-intent"><%= student.intent.humanize %></td>
                  <% end %>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      <% end %>
    </ul>
  <% end %>
</div>
<hr />
<% if policy(:intent).import? %>
  <h2>Import Intents</h2>
  <p>If you would like to import the intents for students in this draw
  please upload a CSV file containing the relevant data below. The CSV
  must have the columns "<%= User.login_attr %>,intent" where the
  intent is either "on_campus" or "off_campus"</p>
  <p>
  <%= simple_form_for @intents_importer, url: import_draw_intents_path(@draw) do |f| %>
    <%= f.input :file, label: 'Upload a CSV', as: :file %>
    <%= f.submit 'Import' %>
  <% end %>
  <hr />
<% end %>
<div style="padding-top: 1em;">
  <% if policy(@draw).bulk_on_campus? %>
        <%= link_to 'Make all undeclared students on campus', bulk_on_campus_draw_path(@draw),
          method: :patch,
          **with_tooltip(text: 'Sets all students who have not declared'\
                        ' their housing intent to living on campus',
                        class_override: 'button secondary') %>
  <% end %>
  <% if policy(@draw).lock_intent? %>
    <div class="lock-intent-form">
      <%= simple_form_for @draw, inner_html: { style: 'display: inline-block;' } do |f| %>
        <%= f.input :intent_locked, as: 'hidden',
          input_html: { value: !@draw.intent_locked } %>
        <%= f.submit lock_intent_btn_label(@draw),
          **with_tooltip(text: lock_intent_btn_tooltip(@draw), class_override: 'button secondary') %>
      <% end %>
    </div>
  <% end %>
  <%= link_to 'Export to CSV', export_draw_intents_path(@draw), class: 'button secondary' if policy(:intent).export? %>
</div>
<%= link_to 'Return to draw', draw_path(@draw) %>