config/routes.rb
# frozen_string_literal: true

# rubocop:disable BlockLength
Rails.application.routes.draw do
  namespace :admin do
    resources :users
    resources :draws
    resources :draw_memberships
    resources :groups
    resources :memberships
    resources :clips
    resources :lottery_assignments
    resources :suites
    resources :rooms
    resources :room_assignments
    resources :buildings
    resources :colleges

    root to: 'users#index'
  end

  devise_for :users
  unauthenticated :user do
    root to: 'colleges#show', id: 'home', as: 'landing_page'
  end
  root to: 'dashboards#show'

  resources :colleges, only: %i(show index new create edit update) do
    patch 'archive'
  end

  shallow do
    resources :buildings do
      resources :suites, except: :index do
        member do
          get 'merge'
          post 'merge', to: 'suites#perform_merge'
          get 'split'
          post 'split', to: 'suites#perform_split'
          post 'unmerge'
        end
        resources :rooms, except: :index do
          member do
            patch 'suite', to: 'rooms#update'
            post 'suite', to: 'rooms#update'
          end
        end
      end
    end
  end

  resource :suite_import, only: %i(create)

  resource :terms_of_service, only: %i(show) do
    patch 'accept'
    patch 'reset'
  end

  resources :masquerades, only: %() do
    collection do
      delete 'end', to: 'masquerades#end', as: 'end'
    end
  end

  resources :users do
    resources :masquerades, only: %i(new)

    member do
      get 'intent', to: 'users#edit_intent', as: 'edit_intent'
      patch 'intent', to: 'users#update_intent', as: 'update_intent'
      get 'edit_password'
      patch 'update_password'
    end

    collection do
      get 'build'
    end
  end

  resources :enrollments, only: %i(new create)

  resources :draws, only: %i(new create show edit update destroy) do
    member do
      patch 'activate'
      post 'duplicate'
      patch 'proceed_to_group_formation'
      post 'reminder'
      patch 'bulk_on_campus'
      get 'lottery_confirmation'
      patch 'start_lottery'
      get 'oversubscription', to: 'draws#oversubscription', as: 'oversub'
      patch 'size_lock/:size', to: 'draws#toggle_size_restrict',
                               as: 'toggle_size_restrict'
      patch 'restrict_all_sizes'
      patch 'lock_all_groups'
      delete 'prune_oversub/:prune_size', to: 'draws#prune', as: 'prune'
      patch 'start_selection'
      get 'results'
      get 'group_export'
      patch 'archive'
    end

    resources :draw_suites, only: %i(index), as: :suites do
      collection do
        get 'edit_collection'
        patch 'update_collection'
      end
    end

    resources :lottery_assignments, only: %i(update create index) do
      collection do
        post 'automatic'
      end
    end

    resource :students, only: %i(edit update), controller: :draw_students do
      collection do
        patch 'bulk_assign'
      end
    end

    resources :groups do
      member do
        put 'finalize'
        put 'lock'
        put 'unlock'
        patch 'make_drawless'
        patch 'skip'
      end
    end

    resource :intents, only: [] do
      get 'report'
      post 'import'
      get 'export'
    end

    resource :suite_assignment, only: %i(new create)
  end

  resources :clips, only: %i(show edit update destroy)

  resources :clip_memberships, only: %i(update destroy)

  resources :groups, controller: 'drawless_groups' do
    collection do
      patch 'archive'
    end

    member do
      put 'lock'
      put 'unlock'
      get 'invite', to: 'memberships#new_invite', as: 'new_invite'
      post 'invite', to: 'memberships#create_invite', as: 'create_invite'
    end
    resources :memberships, only: %i(create update destroy)
    resource :suite_assignment, only: %i(new create destroy)
    resource :clip, only: %i(new create)
    resource :room_assignment, only: %i(new create edit update) do
      collection do
        get 'confirm'
      end
    end
  end

  resource :email_export, only: %i(new create)

  resources :results, only: [] do
    collection do
      get 'students'
      get 'suites'
      get 'export'
    end
  end
end

app/models/group.rb
# frozen_string_literal: true

# Model for Housing Groups
#
# @attr size [Integer] The room size that the Group wants.
# @attr status [String] The state of the group (open, full, finalizing,
#   or locked)
# @attr leader [User] The student that represents the Group.
# @attr members [Array<User>] The members of the group, excluding the leader.
# @attr draw [Draw] The Draw that this Group is in.
# @attr memberships_count [Integer] the number of accepted memberships (counter
#   cache)
# @attr transfers [Integer] the number of transfer students in the group
# @attr lottery_assignment [LotteryAssignment] the lottery assignment for the
#   group
# @attr clip [Clip] The clip that the group is in, if any.
# @attr clip_memberships [Array<ClipMembership>] All clip memberships that the
#   group is associated with, pending or confirmed.
# @attr clip_membership [ClipMembership] The confirmed clip membership for the
#   group, if any.
class Group < ApplicationRecord # rubocop:disable ClassLength
  belongs_to :leader_draw_membership, class_name: 'DrawMembership',
                                      inverse_of: :led_group
  has_one :leader, through: :leader_draw_membership, class_name: 'User',
                   source: :user
  belongs_to :draw
  has_one :clip_membership, -> { where(confirmed: true) }, dependent: :destroy
  has_one :clip, through: :clip_membership
  has_many :clip_memberships, dependent: :destroy
  has_one :suite_assignment, dependent: :destroy
  has_one :suite, through: :suite_assignment
  belongs_to :lottery_assignment
  accepts_nested_attributes_for :suite

  has_many :memberships, dependent: :delete_all
  has_many :full_memberships, -> { where(status: 'accepted') },
           class_name: 'Membership', inverse_of: :group
  has_many :draw_memberships, through: :full_memberships,
                              source: :draw_membership
  has_many :members, through: :draw_memberships, source: :user

  delegate :number, to: :lottery_assignment, prefix: :lottery, allow_nil: true
  delegate :number, to: :suite, prefix: :suite, allow_nil: true
  delegate :building_name, to: :suite, allow_nil: true
  delegate :id, to: :leader, prefix: :leader, allow_nil: true

  enum status: %w(open closed finalizing locked)

  validates :status, presence: true
  validates :leader, presence: true
  validates :size, presence: true,
                   numericality: { greater_than: 0 }
  validates :leader_draw_membership, presence: true,
                                     inclusion:
                                     { in: ->(g) { g.draw_memberships } }
  validates :memberships_count, numericality: { greater_than_or_equal_to: 0 }
  validates :transfers, presence: true,
                        numericality: { greater_than_or_equal_to: 0,
                                        only_integer: true }
  validate :validate_members_count, if: ->(g) { g.size.present? }
  validate :validate_status, if: ->(g) { g.size.present? }
  validate :validate_lottery_assignment,
           if: -> { will_save_change_to_lottery_assignment_id? }

  before_validation :add_leader_to_members,
                    if: ->(g) { g.leader_draw_membership.present? }
  after_save :update_status!,
             if: ->() { saved_change_to_transfers || saved_change_to_size }
  before_update :freeze_lottery,
                if: -> { will_save_change_to_lottery_assignment_id? }
  after_update :remove_clip_memberships,
               if: ->() { changed_draw_with_clip_memberships? }

  after_destroy :destroy_lottery_assignment,
                if: ->(g) { g.lottery_assignment.present? }

  attr_reader :remove_ids

  scope :order_by_lottery,
        -> { joins(:lottery_assignment).order('lottery_assignments.number') }

  scope :active, lambda {
    includes(:leader_draw_membership).where(draw_memberships: { active: true })
  }

  # Generate the group name
  #
  # @return [String] the group's name
  def name(*opts)
    base = "#{leader.full_name}'s Group"
    opt_strs = opts.map { |o| name_str(o) }.compact.join(', ')
    return base unless opt_strs.present?
    "#{base} (#{opt_strs})"
  end

  # Updates the status to match the group size (open when fewer members than
  # the size, and full when they are the same). Uses `update_columns` to avoid a
  # SystemStackError under certain circumstances (skips callbacks).
  def update_status!
    assign_new_status
    return unless status && valid?
    update_columns(status: status) # rubocop:disable Rails/SkipsModelValidations
  end

  # Get the group's membership requests
  #
  # @return [Array<Membership>] the group's memberships with a requested status
  def requests
    memberships.select { |m| m.status == 'requested' }
  end

  # Get the group's membership invitations
  #
  # @return [Array<Membership>] the group's memberships with an invited status
  def invitations
    memberships.select { |m| m.status == 'invited' }
  end

  # Get all of the non-accepted memberships for the group
  #
  # @return [Array<Membership>] the memberships that are not accepted
  def pending_memberships
    memberships.where.not(status: 'accepted')
  end

  # Get the group's members that can be removed
  #
  # @return [Array<User>] the members of the group with the exception of the
  #   group leader
  def removable_members
    members.joins(:draw_membership).where
           .not(draw_memberships: { id: leader_draw_membership_id })
  end

  # Remove specified members
  #
  # @param ids [Array<User>] members of the group
  # @return [Array<User>] the remaining members of the group after deletion
  def remove_members!(ids:)
    ids.delete_if { |u| u == leader.id }
    memberships.joins(:draw_membership)
               .where(draw_memberships: { user_id: ids }).delete_all
    # rubocop:disable Rails/SkipsModelValidations
    decrement!(:memberships_count, ids.size)
    # rubocop:enable Rails/SkipsModelValidations
    update_status!
  end

  # Get the group's locked/finalized members
  #
  # @return [Array<User>] the users who have locked their membership
  def locked_members
    full_memberships.where(locked: true).includes(:user).map(&:user)
  end

  # Check if all members have locked their memberships
  #
  # @return [Boolean] true if the group can be locked
  def lockable?
    (members - locked_members).empty? && members_count == size
  end

  # Check if there are any locked memberships
  #
  # @return [Boolean] true if there are any unlocked members
  def unlockable?
    !locked_members.empty? && suite.nil?
  end

  # Check if the group is full
  #
  # @return [Boolean] true if the group's size equals the number of members
  #   in it
  def full?
    members_count == size
  end

  # Return the lottery number assigned to the group, if present
  #
  # @return [Integer, nil] the number, or nil if it isn't present
  def lottery_number
    return nil unless lottery_assignment
    lottery_assignment.number
  end

  # Check if there is an open invitation to join the provided clip
  #
  # @param [Clip] the clip to check for its invitation status
  # @return [Boolean] true if invited to join the given clip
  def invited_to_clip?(clip)
    clip_memberships.where(clip_id: clip.id, confirmed: false).present?
  end

  # Destroys the group if it contains no members. It is called
  # automatically after a membership in the group is destroyed.
  #
  # @return [Group] the group destroyed or nil if no change
  def cleanup!
    destroy! if existing_memberships.length <= 0
  end

  # For use with simple_form_for's label_method
  #
  # @return [String] the group's name with the size appended
  def to_label
    name(:with_size)
  end

  private

  def name_str(opt)
    case opt
    when :with_size
      Suite.size_str(size)
    when :with_year
      leader.class_year.to_s
    end
  end

  def remove_clip_memberships
    clip_memberships.each(&:destroy)
  end

  # override default attribute getter to include transfers
  def members_count
    return 0 unless memberships_count || transfers
    return memberships_count unless transfers
    return transfers unless memberships_count
    memberships_count + transfers
  end

  def add_leader_to_members
    return if draw_memberships.include?(leader_draw_membership)
    draw_memberships << leader_draw_membership
  end

  def validate_members_count
    return unless members_count > size
    errors.add :members, "can't be greater than the size (#{size})"
  end

  def validate_status
    return unless will_save_change_to_status?
    case status
    when 'open'
      validate_open
    when 'locked'
      validate_locked
    else
      validate_not_open
    end
  end

  def validate_open
    return unless members_count >= size
    errors.add :status, 'can only be open when fewer members than size'
  end

  def validate_not_open
    return if full?
    errors.add :status, "can only be #{status} when members equal size"
  end

  def validate_locked
    validate_not_open
    return if lockable?
    errors.add :status, 'can only be locked when all members have locked'
  end

  def validate_lottery_assignment
    return unless lottery_assignment.present?
    if clip.present?
      validate_lottery_for_clipped
    else
      validate_lottery_for_unclipped
    end
  end

  def validate_lottery_for_clipped
    return if clip == lottery_assignment.clip
    errors.add(:lottery_assignment, 'must belong to the same clip')
  end

  def validate_lottery_for_unclipped
    return if clip.present?
    return if lottery_assignment.groups.length == 1 &&
              lottery_assignment.group == self
    errors.add(:lottery_assignment, 'can only have one group unless clipped')
  end

  def freeze_lottery
    if lottery_assignment_id_in_database.present? &&
       lottery_assignment_id.present?
      handle_abort('Cannot edit lottery assignment once set')
    end
  end

  def changed_draw_with_clip_memberships?
    saved_change_to_draw_id && clip_memberships.present?
  end

  def assign_new_status
    if members_count < size

app/controllers/admin/groups_controller.rb
# frozen_string_literal: true

module Admin
  # Administrate dashboard mirror of the Group controller.
  class GroupsController < Admin::ApplicationController
    def update
      result = GroupUpdater.update(
        group: requested_resource,
        params: group_params
      )
      handle_result(result, :edit)
    end

    def create
      result = GroupCreator.new(params: group_params).create
      handle_result(result, :new)
    end

    private

    def group_params
      p = params.require(:group).permit(:size, :leader_id, :transfers,
                                        :lottery_number, :suite,
                                        :draw_id, :status,
                                        member_ids: [], remove_ids: [],
                                        invitations: [])
      p[:leader] = p.delete(:leader_id)
      p
    end

    def handle_result(result, action)
      result[:msg].each { |flash_type, msg_str| flash[flash_type] = msg_str }
      if result.delete(:redirect_object).present?
        redirect_to admin_group_path(result[:record] || requested_resource)
      else
        render action, locals: { page: Administrate::Page::Form.new(
          dashboard, result[:record] || requested_resource
        ) }
      end
    end
  end
end

app/helpers/groups_helper.rb
# frozen_string_literal: true

# Helper methods for the Groups views
module GroupsHelper
  # Generate the user listing for a group member; includes membership lock
  # status
  #
  # @param member [User] the user
  # @param group [Group] the user's group
  # @return [String] the user listing
  def member_str(member, group)
    membership = member.membership
    locked_str = membership.locked? ? ' (locked)' : ''
    leader_str = member.leader_of?(group) ? ' (leader)' : ''
    link_to(member.full_name, user_path(member)) + leader_str + locked_str
  end

  # Sort an array of groups by lottery number (nil first), then by group leader
  # last name
  #
  # @param groups [Array<Group>] the groups to sort
  # @return [Array<Group>] the sorted groups
  def sort_by_lottery(groups)
    groups.sort_by do |g|
      if g.lottery_number.nil?
        [-Float::INFINITY, g.leader.last_name]
      else
        [g.lottery_number, g.leader.last_name]
      end
    end
  end

  # Displays the status of a group as the capitalization of its current
  # status. In the case of 'closed' it returns Full to maintain the
  # readability.
  #
  # @param [String] the group that's status will be displayed
  # @return [String] the capitalization of the current status
  def display_group_status(group)
    if group.closed?
      'Full'
    elsif group.finalizing?
      'Locking'
    else
      group.status.capitalize
    end
  end

  # Generate the group name with relevant clipping information appended
  #
  # @param [Group] the group needing the appended information
  # @return [String] the group's name
  def clipping_name(group)
    group.name + if group.clip.present?
                   ' (confirmed)'
                 elsif group.clip_memberships.present? && group.clip.blank?
                   ' (invited to clip)'
                 else
                   ''
                 end
  end
end

app/views/groups/_actions.html.erb
<% if policy(group).show? %>
	<%= link_to 'View', draw_group_path(group.draw, group), class: 'button' %>
<% end %>
<% if policy(group).edit? %>
  <%= link_to 'Edit', edit_draw_group_path(group.draw, group), class: 'button' %>
<% end %>
<% if policy(group).destroy? %>
  <%= link_to 'Disband', draw_group_path(group.draw, group, redirect_path: path), method: :delete,
              data: { confirm:  'Are you sure you want to disband this group?' }, class: 'button alert' %>
<% end %>

app/views/groups/_form.html.erb
<%= simple_form_for [draw, group] do |f| %>
  <%= render partial: 'form_fields', locals: {f: f, suite_sizes: suite_sizes, group: group, students: students, leader_students: leader_students } %>
<% end %>

app/views/groups/_form_fields.html.erb
<div class="form-inputs">
  <%= f.input :size, collection: suite_sizes %>
  <% if policy(group).change_leader? %>
    <%= f.input :leader, label_method: :full_name, collection: leader_students %>
  <% end %>
  <% if policy(group).advanced_edit? %>
    <%= f.input :remove_ids, input_html: {'aria-label' => 'Please select users to remove'}, label: 'Users to remove', collection: group.removable_members, label_method: :full_name, as: :check_boxes unless group.removable_members.empty? %>
    <%= f.input :member_ids, input_html: {'aria-label' => 'Please select users to add'}, label: 'Users to add', label_method: :full_name, as: :check_boxes, collection: students %>
    <% if group.persisted? %>
      <%= f.input :transfers, label: '# transfer students' %>
    <% end %>
  <% end %>
</div>

<div class="form-actions">
  <%= f.button :submit %>
</div>

app/views/groups/_secondary_report.html.erb
<% if groups.empty? %>
  <p>There are no groups.</p>
<% else %>
  <ul class="tabs" data-tabs id="group-size-tabs">
    <% groups.keys.sort.each do |size| %>
      <li class="tabs-title<%= groups.keys.sort.first == size ? ' is-active' : '' %>">
        <a href="#size-<%= size %>"><%= headerize_size(size) %></a>
      </li>
    <% end %>
  </ul>
  <div class="tabs-content" data-tabs-content="group-size-tabs">
    <% groups.keys.sort.each do |size| %>
      <div class="tabs-panel<%= groups.keys.sort.first == size ? ' is-active' : '' %>" id="size-<%= size %>">
        <% if groups[size].empty? %>
          <p>No groups of size <%= size %></p>
        <% else %>
          <table aria-label="Group Report" class="group-report-1">
            <thead>
              <tr>
                <th scope="col">Group Leader</th>
                <th scope="col">Lottery #</th>
                <th scope="col">Suite</th>
                <th scope="col">Rooms?</th>
                <th scope="col"></th>
              </tr>
            </thead>
            <tbody>
              <% sort_by_lottery(groups[size]).each do |group| %>
                <tr id="group-<%= group.id %>">
                  <th scope="row" data-role="group-leader"><%= group.leader.full_name %></th>
                  <td data-role="group-lottery"><%= group.lottery_number %></td>
                  <td data-role="group-suite"><%= link_to SuiteDecorator.new(group.suite).name, suite_path(group.suite) if group.suite %> </td>
                  <td data-role="group-room"> <%= group.leader.room.present? ? 'Y' : 'N' %></td>
                  <td class="actions" data-role="group-actions"><%= render partial: actions_partial, locals: { group: group, path: path } %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
        <% end %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/groups/_suites_table.html.erb
<% suites.each do |building, suites_array| %>
  <p id="table-description" class="sr-only">This table lists available suites of the same size as the current group.
    The first column lists the suite number. The second column lists the number of singles in that suite. The third column
    lists the number of doubles in that suite. The fourth column lists the number of common rooms in that suite.</p>
  <p class="h4"><em><%= building.name %></em></p>
  <table aria-label="Compatible Suites" aria-describedby="table-description">
    <thead>
      <tr>
        <th scope="col">Suite #</th>
        <th scope="col">S</th>
        <th scope="col">D</th>
        <th scope="col">C</th>
      </tr>
    </thead>
    <tbody>
      <% suites_array.each do |suite| %>
        <% if policy(suite).show? %>
          <tr>
            <th scope="row"><%= link_to suite.number, suite_path(suite) %></th>
            <td><%= suite.singles.count %></td>
            <td><%= suite.doubles.count %></td>
            <td><%= suite.common_rooms.count %></td>
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/groups/index.html.erb
<% provide(:title, "#{@draw.name} - All Groups") %>
<h1><%= @draw.name %> - All Groups</h1>
<% if @groups.empty? %>
  <p>There are no groups in this draw yet.</p>
<% else %>
  <div class="printable-group-report">
    <% @groups.each do |size, group_array| %>
      <h2><%= headerize_size(size) %></h2>
      <table aria-label="Group Report">
        <thead>
          <tr>
            <th scope="col">Group Leader</th>
            <th scope="col">Other Members</th>
            <% if current_user.admin? %>
              <th scope="col">Transfers</th>
            <% end %>
          </tr>
        </thead>
        <tbody>
          <% group_array.each do |group| %>
            <tr>
              <th scope="row" data-role="group-leader">
                <% if policy(group).show? %>
                  <%= link_to group.leader.full_name, draw_group_path(@draw, group) %>
                <% end %>
              </th>
              <td data-role="group-members"><%= group.members.map(&:full_name).join(', ') %></td>
              <% if current_user.admin? %>
                <td data-role="group-transfers"><%= group.transfers %></td>
              <% end %>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% end %>
  </div>
<% end %>
<% if policy(@draw).show? %>
  <%= link_to 'Return to draw', draw_path(@draw) %>
<% end %>

app/views/groups/show.html.erb
<% provide(:title, @group.name) %>
<%= render partial: 'group_details', locals: { group: @group } %>
<% if policy(@group).view_pending_members? %>
  <% unless @group.requests.empty? %>
    <h2 class="group-requests h4">Requests</h2>
    <ul>
      <% @group.requests.each do |r| %>
        <% if policy(r.user).show? %>
          <li class="group-request">
            <%= link_to r.user.full_name, user_path(r.user) %>
            <% if policy(r).accept? %>
              (<%= link_to 'accept',
               group_membership_path(@group, r, update_action: 'accept'), method: :patch %><%= policy(r).destroy? ? ' / ' : ')' %>
           <% end %>
           <% if policy(r).destroy? %>
             <%= '(' unless policy(r).accept? %><%= link_to 'reject', group_membership_path(@group, r), method: :delete %>)
           <% end %>
          </li>
        <% end %>
      <% end %>
    </ul>
  <% end %>
  <% unless @group.invitations.empty? %>
    <h2 class="group-invitations h4">Invitations</h2>
    <ul>
      <% @group.invitations.each do |i| %>
        <% if policy(i.user).show? %>
          <li class="group-invitation">
            <%= link_to i.user.full_name, user_path(i.user) %>
            <% if policy(i).destroy? %>
              (<%= link_to 'rescind', group_membership_path(@group, i), method: :delete %>)
            <% end %>
          </li>
        <% end %>
      <% end %>
    </ul>
  <% end %>
<% end %>
<hr style="border-color: #DDDDDD;" />
<% if College.current.allow_clipping? %>
  <h2>Clipping</h2>
  <% if @group.clip.present? %>
    <h3 class="clip-information h4">Your Clip</h3>
    <%= render partial: 'clips/clip_details', locals: { clip: @group.clip } %>
    <hr style="border-color: #DDDDDD;" />
  <% else %>
    <p>This group is not in a clip.<p>
    <% if @clip_invites.length.positive? %>
      <h3 class="clip-invites h4">Clip Invitations</h3>
      <ul>
        <% @clip_invites.each do |m| %>
          <li class="clip-invitation" id="clip-membership-<%= m.id %>">
            <%= link_to m.clip.name, clip_path(m.clip) if policy(m.clip).show? %>
            <% if policy(m).accept? %>
              (<%= link_to 'Accept Invitation', clip_membership_path(m), method: :patch %><%= policy(m).reject? ? ' / ' : ')' %>
            <% end %>
            <% if policy(m).reject? %>
              <%= '(' unless policy(m).accept? %><%= link_to 'Reject Invitation', clip_membership_path(m), method: :delete %>)
            <% end %>
          </li>
        <% end %>
      </ul>
    <% end %>
    <%= link_to 'Create a Clip', new_group_clip_path(@group), class: 'button' %>
  <% end %>
  <hr style="border-color: #DDDDDD;" />
<% end %>
<div>
  <% if @membership.present? %>
    <%= link_to 'Accept Invitation', group_membership_path(@group, @membership, update_action: 'accept'), method: :patch, class: 'button' if policy(@membership).accept? %>
    <%= link_to 'Lock Membership', group_membership_path(@group, @membership, update_action: 'finalize'), method: :patch, class: 'button' if policy(@membership).finalize? %>
    <% if policy(@membership).destroy? %>
      <%= link_to 'Leave group', group_membership_path(@group, @membership), method: :delete, class: 'button alert' %>
    <% end %>
  <% end %>
  <%= link_to 'Edit', edit_draw_group_path(@draw, @group), class: 'button secondary' if policy(@group).edit? %>
  <%= link_to 'Request To Join', group_memberships_path(@group, create_action: 'request'), method: :post, class: 'button secondary' if policy(Membership.new(group: @group, user: current_user)).request_to_join? %>
  <%= link_to 'Invite Members', new_invite_group_path(@group), class: 'button secondary' if policy(Membership.new(group: @group, user: current_user)).create_invite? %>
  <%= link_to 'Begin Locking Process for Group', finalize_draw_group_path(@draw, @group), method: :put, data: { confirm: 'This will begin the process of confirming this housing group and cannot be undone. Are you sure you want to proceed?' }, class: 'button' if policy(@group).finalize? %>
  <%= link_to 'Lock Group', lock_draw_group_path(@draw, @group), method: :put, class: 'button alert' if policy(@group).lock? %>

  <% if @group.suite.present? && policy(@group.suite_assignment).destroy? %>
    <%= simple_form_for @group, url: group_suite_assignment_path(@group), method: :delete, html: { class: 'hidden-form' } do |f| %>
      <%= f.input :suite, as: :hidden, input_html: { value: '' } %>
      <%= f.submit 'Remove suite' %>
    <% end %>
  <% end %>
  <% if !@group.suite.present? && policy(@group).reassign_suite? %>
    <%= link_to 'Assign suite', new_group_suite_assignment_path(@group), class: 'button' %>
  <% end %>

  <%= link_to 'Unlock All Members', unlock_draw_group_path(@draw, @group), method: :put, class: 'button alert' if policy(@group).unlock? %>

  <% if policy(RoomAssignment.from_group(@group)).new? %>
    <%= link_to 'Assign rooms', new_group_room_assignment_path(@group), class: 'button' %>
  <% end %>
  <% if policy(RoomAssignment.from_group(@group)).edit? %>
    <%= link_to 'Edit room assignments', edit_group_room_assignment_path(@group), class: 'button' %>
  <% end %>

  <% if policy(@group).make_drawless? %>
    <%= link_to 'Make special group', make_drawless_draw_group_path(@draw, @group), method: :patch, data: { confirm: 'Are you sure you want to remove this group and its members from the draw?' },
      **with_tooltip(text: 'Remove this group and its members from the draw and convert it to a special group.', class_override: 'button alert') %>
  <% end %>

  <%= link_to('Disband', draw_group_path(@draw, @group), method: :delete, data: { confirm: 'Are you sure you want to disband this group?' }, class: 'button alert') if policy(@group).destroy? %>
</div>
<%= link_to 'Return to draw', draw_path(@draw) %>

<% content_for :sidebar do %>
  <h1 class="h3">Compatible Suites</h1>
  <h2 class="h4"><%= @same_size_groups_count %> <%= 'group'.pluralize(@same_size_groups_count) %> of size <%= @group.size %></h2>
  <h2 class="h4"><%= @compatible_suites_count %> available <%= size_str(@group.size).capitalize.pluralize(@compatible_suites_count) %></h2>
  <% unless @compatible_suites_count.zero? %>
    <%= render partial: 'groups/suites_table', locals: { suites: @compatible_suites.group_by(&:building) } %>
  <% end %>
<% end %>